### ISSUE TITLE
Bug with VoidCraft and Baubles?

### ISSUE THREAD

**Issue by ravendm5** [Tamaized/VoidCraft#56] opened 2016-10-23 22:08 UTC
It seems that every time I read the Void Vade Mecum it causes a de-sync between the normal inventory and the baubles inventory and only the baubles inventory can be used to move items and visually update the inventory screen.

**Comment by Tamaized** [comment] 2016-10-23 22:14
I'll look into it when I can, currently I don't have any time right now.

**Comment by Tamaized** [comment] 2016-10-24 18:01
I'm unable to reproduce this with Baubles-1.10.2-1.3.BETA11 on both a singleplayer world and on a server

**Comment by Tamaized** [comment] 2016-10-25 19:55
Finally was able to reproduce this

**Comment by Tamaized** [comment] 2016-10-26 22:03
Seems to be fixed in my testing, feel free to reopen this if it occurs in 0.9.9, after I release it of course.

**Closed by Tamaized** 2016-10-26 22:03 UTC
Labels: Bug
