### ISSUE TITLE
voidcraft:blocks/aiblock updating too frequently

### ISSUE THREAD

**Issue by LemADEC** [Tamaized/VoidCraft#101] opened 2017-03-12 18:28 UTC
As of VoidCraft-1.10.2-0.17.4.jar, after 1 week of testing on our dedicated server, we've noted that 92% of all server updates are related to "voidcraft:blocks/aiblock".
More specifically, out of 12000000 prism events, only 936000 are not related to this block.

**Comment by Tamaized** [comment] 2017-03-12 18:34
is it clear what method is being called? the only thing I can think of is this but there are checks for when they really do need to change state https://github.com/Tamaized/VoidCraft/blob/1.11.2/src/main/java/Tamaized/Voidcraft/xiaCastle/logic/XiaCastleLogicHandler.java#L115

**Comment by LemADEC** [comment] 2017-03-12 19:49
It was observed on 1.10.2, here the data attached to it:
```
{"Original":{"ContentVersion":1,"BlockState":{"ContentVersion":2,"BlockState":"voidcraft:blocks/aiblock[state=0]"},"UnsafeData":{"ForgeData":{"SpongeData":{}},"x":48,"y":79,"z":82,"id":"tileEntityAIBlock","state":0}},"Replacement":{"ContentVersion":1,"BlockState":{"ContentVersion":2,"BlockState":"minecraft:air"}}}
```

**Comment by LemADEC** [comment] 2017-03-12 19:53
Actually, there's only 2 cases, here's the second one:
```
{"Original":{"ContentVersion":1,
"BlockState":{"ContentVersion":2,"BlockState":"voidcraft:blocks/aiblock[state=0]"},
"UnsafeData":{"ForgeData":{"SpongeData":{}},"x":56,"y":79,"z":82,"id":"tileEntityAIBlock","state":0}},
"Replacement":{"ContentVersion":1,
"BlockState":{"ContentVersion":2,"BlockState":"minecraft:air"}}}
```

That's on a fresh map.

**Comment by Tamaized** [comment] 2017-03-12 19:55
Yea I'm not quite sure what the cause is, the tile entity is no different from any other, infact it's less than others as it really only contains 1 field (the state) and 1 method is used, which is used to trigger certain events such as damaging the Avatar of Herobrine but that's not updated each tick, it's called from `EntityHerobrineFireball` and only on impact. In other words there's really nothing I can do here that's clear to me anyway, if it's being updated more than once per tick as it seems to be from what i'm gathering here then I would pretty much blame sponge at this point because both the TileEntity and the Block itself contain nothing that deals with updates per tick.

**Comment by Tamaized** [comment] 2017-03-12 19:56
As for the data, no idea what it means by "unsafe", that's literally just NBT data

**Comment by LemADEC** [comment] 2017-03-12 20:06
Any fast way to go in creative to those coordinates in the Void dimension and see what's going on?

**Comment by Tamaized** [comment] 2017-03-12 20:07
The Blocks only exist in the Xia dimension, which only generates when you first enter there from the Xia Portal, if these blocks are anywhere else then we have a very very serious problem.

**Comment by Tamaized** [comment] 2017-03-12 20:08
And based on the NBT data shown, those coords seem correct for the Xia DIM as they're all preset.

**Comment by LemADEC** [comment] 2017-03-12 20:13
It's a fresh map, nobody went outside the overworld. Only the spawn area would have been generated.
How can I get into that portal?

**Comment by Tamaized** [comment] 2017-03-12 20:14
You can spawn it in with creative, the normal way would be using a 3x3x2 layer of soft bedrock where the 2nd layer center is missing and you toss a Void Star into it.

**Comment by LemADEC** [comment] 2017-03-12 20:16
When I throw the Void Star into it, the portal is replaced by fire from the lightning

**Comment by Tamaized** [comment] 2017-03-12 20:18
Quite odd, i'd again blame sponge on that since that can't happen, or shouldn't, in vanilla Forge. Spawn the Xia portal in manually, should be in the VoidCraft creative tab with normal creative or you can find it if you use JEI/NEI of the sort. it would be the red one.

**Comment by Tamaized** [comment] 2017-03-12 20:18
You can also try checking those coords in the overworld if you want to make sure they dont exist in the overworld at all. can use /tp X Y Z

**Comment by LemADEC** [comment] 2017-03-12 20:22
Spawn protection was preventing me to enter the portal, forgot that :).
The AI blocks are touching fluid, that's probably the issue.

**Comment by Tamaized** [comment] 2017-03-12 20:23
No, that wouldn't make any sense. There's no reason at all for the two to interact.

**Comment by LemADEC** [comment] 2017-03-12 20:38
So placing a Void Brick block against the AI protects it from the fluid trying to replace it and stop the spam.
Sadly, the structure seems to regenerate when I enter the dimension or something a like.

**Comment by Tamaized** [comment] 2017-03-12 20:39
So Fluids cause block updates, if you enter the void i'm sure you'll have a ton more spam? Can enter there using the gray portal from the creative tab.

**Comment by LemADEC** [comment] 2017-03-12 21:02
Only AIblock has the spam effect apparently
![image](https://cloud.githubusercontent.com/assets/4776032/23835885/6288903e-076f-11e7-9ee4-a236ca7b6175.png) ![image](https://cloud.githubusercontent.com/assets/4776032/23835887/65c75b7c-076f-11e7-9a92-7762930347da.png)

**Comment by Tamaized** [comment] 2017-03-12 21:03
can you try another test using a tile entity next to the fluid? such as one of my machines. (Don't use the inert infusion altar as it isnt a tileentity)

**Comment by Tamaized** [comment] 2017-03-12 21:08
On a side note, did a test myself using vanilla forge, `TileEntityAIBlock#onUpdate()` only fired once per tick without touching Liquid Void and again fire only once per tick while touching Liquid Void. This is obviously not an issue on my end.

**Comment by LemADEC** [comment] 2017-03-12 21:10
StarForge and Void Blast Furnace don't reproduce the issue.
From what I've seen the event happens once per tick. The initial measure was from 3+ days of uptime.

**Comment by Tamaized** [comment] 2017-03-12 21:12
So this may be perfectly normal behavior, it's just a case of only a few tile entities existed in the world at the time and it just so happens two of those were related to AIBlock so it's tracked twice as much as everything else I guess?

**Comment by LemADEC** [comment] 2017-03-12 21:19
It seems specific to that fluid and block combo. I can't reproduce with vanilla water and lava.

**Comment by Tamaized** [comment] 2017-03-12 21:21
Yea i'm not sure why, as I did the non-SpongeForge test already and the issue doesn't exist there. Makes no sense at all why it would only be this block, there really isn't anything different about this block from any other.

**Comment by Tamaized** [comment] 2017-03-12 21:24
You say you're testing events being fired yes? Is it clear what event in particular is being tracked?

**Comment by LemADEC** [comment] 2017-03-12 21:29
I'm checking the DB filling up with events related to AIblock.
It only happens when I'm outside the dimension. As soon, as I enter it, no more events appear.
Could it be a world object leak or something that keep the dimension half loaded?

**Comment by Tamaized** [comment] 2017-03-12 21:32
I don't keep it loaded and I have it set for Forge to not keep it loaded as well here https://github.com/Tamaized/VoidCraft/blob/1.11.2/src/main/java/Tamaized/Voidcraft/VoidCraft.java#L341

It's possible I suppose for another mod, plugin, or again SpongeForge, to be loading it in a weird way.

**Comment by LemADEC** [comment] 2017-03-12 21:36
All dimensions are loaded at boot, without even a player connecting.

**Comment by Tamaized** [comment] 2017-03-12 21:38
ah, turns out im retarded and I have my handleVisual method running even if the instance isn't running...
https://github.com/Tamaized/VoidCraft/blob/1.11.2/src/main/java/Tamaized/Voidcraft/xiaCastle/logic/XiaCastleLogicHandler.java#L69

I doubt this will fix the issue but it's possible it might. I'll change this and get a new build out.

**Comment by LemADEC** [comment] 2017-03-12 22:07
Nice!
I guess it's under curse review now?

**Comment by Tamaized** [comment] 2017-03-12 22:09
yea pretty much, still fixing some conflicts in the 1.10.2 branch but should be out soon. After 0.17.6 goes out would you mind testing it with that and report back here?

**Comment by LemADEC** [comment] 2017-03-12 22:16
Will do

**Comment by Tamaized** [comment] 2017-03-12 22:35
I.. forgot to turn off my dev stuff (which had a hardcoded dimension value of -4 so this would conflict with any mod that adds a dimension with ID -4) getting another build out to turn this off.. would be 0.17.7. >.>

**Comment by LemADEC** [comment] 2017-03-13 08:51
As of VoidCraft-1.10.2-0.17.7.jar, the aiblock event are no longer showing up.
According to forge, there's still updates going on the Xia dimension:
```
[04:42:01] [Server thread/INFO]: Dim 0§r : Mean tick time: §r6.033§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim -2§r : Mean tick time: §r0.304§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim 51§r : Mean tick time: §r0.275§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim 50§r : Mean tick time: §r0.269§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim -54§r : Mean tick time: §r0.268§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim -51§r : Mean tick time: §r0.263§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim -52§r : Mean tick time: §r0.269§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim 14§r : Mean tick time: §r0.263§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim -50§r : Mean tick time: §r0.258§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim 13§r : Mean tick time: §r0.256§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim 53§r : Mean tick time: §r0.257§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim 52§r : Mean tick time: §r0.261§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim -53§r : Mean tick time: §r0.260§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim -1§r : Mean tick time: §r0.262§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim 1§r : Mean tick time: §r0.259§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim -3§r : Mean tick time: §r5.332§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Dim 5§r : Mean tick time: §r0.282§r ms. Mean TPS: §r20.000§r
[04:42:01] [Server thread/INFO]: Overall§r : Mean tick time: §r16.075§r ms. Mean TPS: §r20.000§r
```
That's with only 1 player online, in the overworld.
Dim -3 is Xia.

**Comment by Tamaized** [comment] 2017-03-13 09:20
That would most likely be the XiaCastleLogicHandler doing its validation checks which is normal.

**Comment by LemADEC** [comment] 2017-03-13 20:13
What I read is DIM-3 using ~10% CPU time while no player is in it.

**Comment by Tamaized** [comment] 2017-03-13 20:17
Yea that's quite odd.
The only thing that can run at that point in time starts here:
https://github.com/Tamaized/VoidCraft/blob/1.11.2/src/main/java/Tamaized/Voidcraft/world/dim/Xia/WorldProviderXia.java#L39

which leads here:
https://github.com/Tamaized/VoidCraft/blob/1.11.2/src/main/java/Tamaized/Voidcraft/xiaCastle/logic/XiaCastleLogicHandler.java#L58

And because running is false at this point in time, we lead here:
https://github.com/Tamaized/VoidCraft/blob/1.11.2/src/main/java/Tamaized/Voidcraft/xiaCastle/logic/XiaCastleLogicHandler.java#L110-L113

which won't be executing anything at all since it requires a player to exist in the dimension.
Not really sure what would be using that much processing power

**Comment by Tamaized** [comment] 2017-03-13 20:18
Actually, looking at the validation... the first check is missing the check for if running is true... shit that's it alright. I'll get ANOTHER fix out lol hang on

**Comment by Tamaized** [comment] 2017-03-13 20:47
On a side note, I believe this missing check may have been a cause for the weird AIBlock issues you were having since the stop method would have forced the blocks to update, and this was only possible while nobody is in the dimension. Yea that's a rather nasty large bug, glad you found this.

**Comment by LemADEC** [comment] 2017-03-13 21:24
You're quite welcome :).

**Comment by Tamaized** [comment] 2017-03-13 21:25
do let me know if this truly does fix it though since you've already got the tools and past data ready to go to check and compare against.

**Comment by LemADEC** [comment] 2017-03-13 23:12
Xia lag is gone when outside the dimension. Still weird that it takes 3+ ms when I'm in there.
Also, I've never seen VoidCraft mobs spawning in Xia. Do I miss a precondition?

**Comment by Tamaized** [comment] 2017-03-13 23:20
Xia is a place to fight some bosses within the mod, no mobs at all spawn in there, as for the 3ms while in there, you can blame the ai stuff going on in there but that one I cant do anymore about as it makes the entire place function. Anywho, as the giant issue is fixed I feel it's safe to close this :)

**Closed by Tamaized** 2017-03-13 23:20 UTC
Labels: Bug, Possible fix needs testing, Priority, Sponge
